config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :reastaurants
  get 'pages/about'
  get 'pages/contact'
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reastaurant.rb
class Reastaurant < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/reastaurants_controller.rb
class ReastaurantsController < ApplicationController
  before_action :set_reastaurant, only: [:show, :edit, :update, :destroy]

  # GET /reastaurants
  # GET /reastaurants.json
  def index
    @reastaurants = Reastaurant.all
  end

  # GET /reastaurants/1
  # GET /reastaurants/1.json
  def show
  end

  # GET /reastaurants/new
  def new
    @reastaurant = Reastaurant.new
  end

  # GET /reastaurants/1/edit
  def edit
  end

  # POST /reastaurants
  # POST /reastaurants.json
  def create
    @reastaurant = Reastaurant.new(reastaurant_params)

    respond_to do |format|
      if @reastaurant.save
        format.html { redirect_to @reastaurant, notice: 'Reastaurant was successfully created.' }
        format.json { render :show, status: :created, location: @reastaurant }
      else
        format.html { render :new }
        format.json { render json: @reastaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reastaurants/1
  # PATCH/PUT /reastaurants/1.json
  def update
    respond_to do |format|
      if @reastaurant.update(reastaurant_params)
        format.html { redirect_to @reastaurant, notice: 'Reastaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @reastaurant }
      else
        format.html { render :edit }
        format.json { render json: @reastaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reastaurants/1
  # DELETE /reastaurants/1.json
  def destroy
    @reastaurant.destroy
    respond_to do |format|
      format.html { redirect_to reastaurants_url, notice: 'Reastaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reastaurant
      @reastaurant = Reastaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reastaurant_params
      params.require(:reastaurant).permit(:name, :adress, :phone, :website, :image)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :adress, :phone, :website, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reastaurants_helper.rb
module ReastaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

app/views/layouts/_footer.html.erb
<p>copyright Raj Bista</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Yelpdemo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        <li><a href="/pages/about">About <span class="sr-only">(current)</span></a></li>
        <li><a href="/pages/contact">Contact</a></li>
         
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelpdemo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/bootstrap' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/pages/about.html.erb
<h1> welcome to test app</h1>
<h2>this is a sample <a href="http://www.baserails.com">baseline</a> application on ruby on rails programming
sign up and start learning today!</h2>

app/views/pages/contact.html.erb
 
 <h1>We would love to hear from you</h1>
 <p>contact us at rajbista.com</p>
 

app/views/reastaurants/_form.html.erb
<%= form_for(@reastaurant, :html => { multipart: true }) do |form| %>
  <% if reastaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reastaurant.errors.count, "error") %> prohibited this reastaurant from being saved:</h2>

      <ul>
      <% reastaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :adress %><br>
    <%= form.text_field :adress, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %><br>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :website %><br>
    <%= form.text_field :website, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :image %><br>
    <%= form.file_field :image, class: "form-control"%>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reastaurants/edit.html.erb
<h1>Editing Reastaurant</h1>

<%= render 'form', reastaurant: @reastaurant %>

<%= link_to 'Show', @reastaurant %> |
<%= link_to 'Back', reastaurants_path %>

app/views/reastaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reastaurants</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reastaurants.each do |reastaurant| %>
      <tr>
        <td><%= reastaurant.name %></td>
        <td><%= reastaurant.adress %></td>
        <td><%= reastaurant.phone %></td>
        <td><%= reastaurant.website %></td>
        <td><%= link_to 'Show', reastaurant, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_reastaurant_path(reastaurant), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', reastaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reastaurant', new_reastaurant_path, class: "btn btn-link" %>

app/views/reastaurants/new.html.erb
<h1>New Reastaurant</h1>

<%= render 'form', reastaurant: @reastaurant %>

<%= link_to 'Back', reastaurants_path, class: "btn btn-link" %>

app/views/reastaurants/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @restaurant.image_url %>

<p>
  <strong>Name:</strong>
  <%= @reastaurant.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @reastaurant.adress %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @reastaurant.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @reastaurant.website %>
</p>

<%= link_to 'Edit', edit_reastaurant_path(@reastaurant), class: "btn btn-link" %> |
<%= link_to 'Back', reastaurants_path, class: "btn btn-link" %>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, :html => { local: true}) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :adress %><br>
    <%= form.text_field :adress, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :phone %><br>
    <%= form.text_field :phone , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :website %><br>
    <%= form.text_field :website, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %><br>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.adress %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.website %></td>
        <td><%= link_to 'Show', restaurant, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-link" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @restaurant.adress %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @restaurant.website %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>